language: python

env:
    matrix:
        - TOX_ENV=py26
        - TOX_ENV=py27
        - TOX_ENV=py32
        - TOX_ENV=py33
        - TOX_ENV=py34
        - TOX_ENV=pypy
        - TOX_ENV=docs
        - TOX_ENV=pep8
        - TOX_ENV=py3pep8

install:
    - pip install coveralls tox

script:
    - tox -e $TOX_ENV

after_success:
    - coveralls

notifications:
    irc:
        channels: "irc.freenode.net#cryptography-dev"
        use_notice: true
        skip_join: true
